# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'news-engine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for news-engine
  pod 'Toast-Swift', '~> 3.0.1'     # https://github.com/scalessec/Toast-Swift
  pod 'Alamofire'                   # https://github.com/Alamofire/Alamofire
  pod 'SwiftyJSON'                  # https://github.com/SwiftyJSON/SwiftyJSON
  pod 'Kingfisher'
  
  target 'news-engineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'news-engineUITests' do
    # Pods for testing
  end

end
